name: Build
on:
  workflow_call:
    outputs:
      version:
        description: "Calculated version of the build"
        value: ${{jobs.build.outputs.version}}
      versionExists: 
        description: "If this run should create a new version"
        value: ${{jobs.build.outputs.versionExists}}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      versionExists: ${{ steps.generate-version.outputs.skipped }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Conventional Changelog Action
        id: generate-version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          preset: "angular"
          release-count: "10"
          git-push: false
          skip-commit: true
          skip-on-empty: true

      - name: apply version
        if: (!steps.generate-version.outputs.skipped)
        run: |
          sed -i 's/"version": ".*",/"version": "${{ env.VERSION }}",/' ./package.json
          sed -i 's/"version": ".*",/"version": "${{ env.VERSION }}",/' ./app/package.json
        env:
          VERSION: ${{ steps.generate-version.outputs.version }}

      - name: Build
        run: yarn run build

      - name: Package artifact
        uses: actions/upload-artifact@v2
        with:
          name: package-${{ env.VERSION }}
          path: ./dist
        env:
          VERSION: ${{ steps.generate-version.outputs.version }}
