name: Build
on:
  workflow_call:
    outputs:
      version:
        description: "Calculated version of the build"
        value: ${{jobs.build.outputs.version}}
      skippedVersionCreation: 
        description: "If a new version was not created"
        value: ${{jobs.build.outputs.skippedVersionCreation}}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      skippedVersionCreation: ${{steps.generate-version.outputs.skipped}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Validate commit message
        uses: wagoid/commitlint-github-action@v4

      - name: Genreate Version and Changelog
        id: generate-version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          preset: "angular"
          release-count: "10"
          git-push: false
          skip-commit: true
          skip-on-empty: true

      - name: apply version
        if: (steps.generate-version.outputs.skipped == 'false')
        run: |
          sed -i 's/"version": ".*",/"version": "${{ env.VERSION }}",/' ./package.json
          sed -i 's/"version": ".*",/"version": "${{ env.VERSION }}",/' ./app/package.json
        env:
          VERSION: ${{ steps.generate-version.outputs.version }}

      - name: Build
        run: yarn run build

      - name: Create zip
        working-directory: ./dist
        run: |
          zip -r ./deploy.zip ./*

      - name: Package artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./dist/*
