name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package:
    needs: build
    if: (needs.build.outputs.skippedVersionCreation == 'false')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts/

      - name: Create tag
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Creating tag '$TAG'"
          git tag "$TAG" "${{github.sha}}"
          git push origin "$TAG"
        env:
          TAG: "v${{ needs.build.outputs.version}}"

      - name: Create release
        if: github.ref == 'refs/heads/main'
        run: |
          gh release create "$TAG" -p -n "$CHANGELOG" './artifacts/package.zip #Deploy package'
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAG: ${{ needs.build.outputs.version}}
          CHANGELOG: ${{ steps.generate-version.outputs.clean_changelog }}
