name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: yarn
      
      - name: Install dependencies
        run: yarn install

      - name: Conventional Changelog Action
        if: github.ref == 'refs/heads/main'
        id: generate-version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          preset: "angular"
          release-count: "10"
          skip-commit: true
          skip-version-file: true
          skip-git-pull: true

      - name: Build
        run: yarn run build

      - name: Create release
        if: github.ref == 'refs/heads/main'
        run: |
          gh release create "$TAG" -p -n "$CHANGELOG" ./dist/*
        env: 
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAG: ${{ steps.generate-version.outputs.tag }}
          CHANGELOG: ${{ steps.generate-version.outputs.clean_changelog }}
