name: CI

on:
  push:
      branches:
        - main
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      tag-name: ${{needs.build.outputs.tag-name}}
      new-version: ${{needs.build.outputs.new-version}}
      changelog: ${{needs.build.outputs.changeLog}}