name: Release
on:
  workflow_call:
    inputs:
      tag-name:
        required: true
        type: string
      new-version:
        required: true
        type: string
      changeLog:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v2
        with:
          name: package
          path: artifacts/
      
      - name: debug
        run: echo "name=${{inputs.version}}\ntag=${{inputs.tag}}\nbody=${{inputs.changelog}}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{inputs.changeLog}}
          prerelease: true
          name: ${{inputs.new-version}}
          tag_name: refs/tags/${{inputs.tag-name}}
          files: artifacts/*