name: Release
on:
  release:
    types: [published]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  release-sandbox:
    if: github.event_name == 'prerelease'
    runs-on: ubuntu-latest
    steps:
      - run: echo "magically deploy to sandbox"

  release-prod:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - run: echo "magically deploy to prod"
