name: Test create release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        run: |
          gh release create "${{needs.build.outputs.tag-name}}" -p
        env: 
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}